import Head from "next/head";
import React from "react";
import CallToAction from "../../components/UI/CallToAction";
import Footer from "../../components/UI/Footer";
import Navbar from "../../components/UI/Navbar";
import SectionHead from "../../components/UI/SectionHead";
import CoachingAstrology from "../../components/Services/CoachingAstrology";
import FollowUp from "../../components/Services/FollowUp";
import Synastry from "../../components/Services/Synastry";

const Services = () => {
  return (
    <div>
      <Head>
        <title>Services | Easy Astrology By Zoée</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo-color.png" />
      </Head>

      <Navbar />

      <main className="text-white">
        <SectionHead title={"Coaching Astrology Consultation - 150 USD"} />

        <div className="bg-green lg:py-20 py-14">
          <div className="container-deep lg:text-2xl sm:text-xl text-lg">
            <CoachingAstrology />
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};
export default Services;
