import Head from "next/head";
import Link from "next/link";
import React from "react";
import Footer from "../../components/UI/Footer";
import Navbar from "../../components/UI/Navbar";
import SectionHead from "../../components/UI/SectionHead";
import Tick from "../../components/UI/Tick";

const Followup = () => {
  return (
    <div>
      <Head>
        <title>Follow-up Consultation | Easy Astrology By Zoée</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo-color.png" />
      </Head>

      <Navbar />

      <main className="text-white">
        <SectionHead title={"Follow-up Consultation (50 USD)"} />

        <div className="bg-gray lg:py-20 py-14">
          <div className="container-deep xl:text-2xl sm:text-xl text-lg">
            <div>
              <div>
                <div className="mb-5 xl:text-4xl text-3xl font-bold">
                  What is it?
                </div>

                <div>
                  The goal is simple: follow-up your <i>self-growth progress</i>{" "}
                  and make sure the previous consultation was <i>effective</i>.
                  But it will also give you <strong>additional advices</strong>,
                  answer any of your <strong>questions</strong> and bring you
                  more <strong>guidance</strong> and <strong>support</strong> on
                  your journey.
                </div>

                <div className="sm:mt-5 mt-3">
                  You need to have done a{" "}
                  <strong>
                    <i>Coaching Astrology Consultation</i>
                  </strong>{" "}
                  or a{" "}
                  <strong>
                    <i>Synastry Consultation</i>
                  </strong>{" "}
                  with me before.
                </div>
              </div>

              <div className="mt-12">
                <div className="mb-5 xl:text-4xl text-3xl font-bold">
                  Is It For You?
                </div>

                <div>Do you want to…</div>

                <ul className="sm:mt-5 mt-3 italic">
                  <li>
                    <span className="mr-1 not-italic font-bold">
                      <Tick />
                    </span>{" "}
                    Answer more questions about your chart
                  </li>
                  <li>
                    <span className="mr-1 not-italic font-bold">
                      <Tick />
                    </span>{" "}
                    Clear doubts you have about your yourself and your progress
                  </li>
                  <li>
                    <span className="mr-1 not-italic font-bold">
                      <Tick />
                    </span>{" "}
                    Explore more in depth your chart
                  </li>
                  <li>
                    <span className="mr-1 not-italic font-bold">
                      <Tick />
                    </span>{" "}
                    Get support and guidance on your self-growth journey
                  </li>
                </ul>

                <div className="sm:mt-5 mt-3">
                  You have replied “yes” to at least one of those questions.
                  Then the{" "}
                  <strong>
                    <i>Follow-up Consultation</i>
                  </strong>{" "}
                  is for you.
                </div>
              </div>

              <div className="mt-12">
                <div className="mb-5 xl:text-4xl text-3xl font-bold">
                  What Will You Get?
                </div>
                <ul>
                  <li>
                    <span className="mr-1 not-italic font-bold">
                      <Tick />
                    </span>{" "}
                    A <strong>30 to 45 min </strong>online follow-up
                    consultation with me.
                  </li>

                  <li>
                    <span className="mr-1 not-italic font-bold">
                      <Tick />
                    </span>{" "}
                    Bonus: A <strong>recording</strong> of the consultation sent
                    just after.
                  </li>
                </ul>
              </div>

              <div className="sm:mt-20 mt-10 flex justify-center">
                <button className="sm:text-2xl text-xl sm:px-12 px-8 sm:py-6 py-4 border-2 border-white hover:bg-white hover:text-black sm:font-bold font-semibold smooth rounded-lg hover:scale-105">
                  I Want To Continue My Self-Growth Journey
                </button>
              </div>

              <div className="mt-6 xl:text-xl text-lg text-center">
                Please read the{" "}
                <Link
                  href="/disclaimer"
                  className="underline font-bold hover:opacity-80 smooth"
                >
                  disclaimers
                </Link>{" "}
                before booking a consultation.
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};
export default Followup;
