import Head from "next/head";
import Image from "next/image";
import React from "react";
import CallToAction from "../components/UI/CallToAction";
import Footer from "../components/UI/Footer";
import Navbar from "../components/UI/Navbar";
import SectionHead from "../components/UI/SectionHead";

const OutBoundLink = ({ children, href }) => (
  <a
    className="font-bold underline smooth hover:opacity-80 cursor-pointer"
    target={"_blank"}
    rel="noreferrer noopener"
    href={href}
  >
    {children}
  </a>
);

const About = () => {
  return (
    <div>
      <Head>
        <title>About | Easy Astrology By Zoée</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo-color.png" />
      </Head>

      <Navbar />

      <main className="text-white">
        <SectionHead title={"About Me"} />

        <div className="bg-green lg:py-20 py-14">
          <div className="container relative">
            {/* Section 1 */}
            <div className="lg:grid grid-cols-3 flex flex-col-reverse">
              <div className="col-span-2 flex lg:pr-20 items-center">
                <div className="lg:text-xl text-lg">
                  <div className="mb-5 font-bold lg:text-3xl text-xl">
                    Who am I?
                  </div>
                  <div>
                    I’m Zoée, astrologer, consultant and content creator but not
                    only.
                  </div>
                  <div className="mt-5">
                    I help people to <u>truly</u> understand themselves and{" "}
                    <i> change their life</i> with astrology and give them{" "}
                    <b>practical keys</b> to reach happiness. All of this using
                    multiples ancient and moderns astrology techniques.
                  </div>

                  <div className="mt-5">
                    What I am doing outside of astrology? So many things! For
                    example, I love reading books on many subjects: psychology,
                    holistic medicines, spirituality (but mainly astrology).
                  </div>

                  <div className="mt-5">
                    Simply, I love <i>learning and deepening</i> my astrology
                    knowledge and skills! Because my passion for it constantly
                    motivates me to progress and learn.
                  </div>

                  <div className="mt-5">
                    Fun fact: I did breakdance for 6 years (it&apos;s the dance
                    you spin on your head). But you probably wonder tell me
                    “what does that have to do with astrology?”.
                  </div>

                  <div className="mt-5">
                    Well, I learned <b>discipline</b> and <b>tenacity</b>.
                    “Never give up until you have achieved your goals”. It’s why
                    I chose to follow my passion and take the challenging way of
                    becoming an astrologer.
                  </div>

                  <div className="mt-5">
                    Oh, and I am also passionate about cooking. I love cooking
                    for my family and friends. I just love serving others. But
                    what I love more than anything is to make them happy and
                    satisfied (just like my clients).
                  </div>

                  <div className="mt-5">
                    Come on, a last passion… I love art! Painting in particular.
                    I try to understand the influence of colors, lines, and
                    shapes on others. And in astrology? I try to understand the
                    influence of the celestial bodies on humans behaviors,
                    traits, health and emotions and on the world.
                  </div>

                  <div className="mt-5">
                    One last thing, <b>honesty</b> is one of my most important
                    values. So if I see that I can&apos;t help you, I will NEVER
                    sell you my services (I really hate those manipulators who
                    just want to make money). I only work with people I know I
                    can help.
                  </div>
                </div>
              </div>
              <div className="col-span-1 lg:flex hidden items-center justify-end">
                <Image
                  className="rounded-full"
                  src="/images/about-face.jpeg"
                  alt=""
                  width={340}
                  height={400}
                />
              </div>

              <div className="lg:hidden flex justify-center mb-10">
                <Image
                  className="rounded-full"
                  src="/images/about-face.jpeg"
                  alt=""
                  width={200}
                  height={200}
                />
              </div>
            </div>

            {/* Section 2 */}
            <div className="lg:grid flex-col grid-cols-3 lg:mt-32 mt-14">
              <div className="col-span-1 lg:flex hidden items-center">
                <Image
                  className="rounded-full"
                  src="/images/about-face.jpeg"
                  alt=""
                  width={340}
                  height={400}
                />
              </div>
              <div className="lg:hidden flex justify-center mb-10">
                <Image
                  className="rounded-full"
                  src="/images/about-face.jpeg"
                  alt=""
                  width={200}
                  height={200}
                />
              </div>

              <div className="col-span-2 flex lg:pl-20 items-center">
                <div className="lg:text-xl text-lg">
                  <div className="mb-5 font-bold lg:text-3xl text-xl">
                    My Story With Astrology
                  </div>
                  <div>
                    Everything started when I was 8 years old. My mom gave me a
                    little paper calendar. It was the first time I discovered my
                    Sun sign. I immediately thought “What?! Why I’m a bull?”
                    (yes, I’m a Taurus haha).
                  </div>

                  <div className="mt-5 font-bold">
                    It was the first time of my life I heard about astrology.
                  </div>

                  <div className="mt-5">
                    Then I kept on <u>trying to understand</u> the other Sun
                    signs of my family. How do they behave? Why do they get
                    along well? Why they don’t?
                  </div>

                  <div className="mt-5">
                    At around 14 years old, I discovered again astrology. Like
                    most of the people, it was through those stupid{" "}
                    <i>Sun sign astrology</i> social media post (I’m sure you
                    know what I’m talking about).
                  </div>

                  <div className="mt-5">
                    Again, I was trying find a logic in the zodiac signs
                    compatibilities. My mind was restless.{" "}
                    <b>I couldn’t stop thinking about it.</b>
                  </div>

                  <div className="mt-5">
                    But everything changed one day, when I was 16 years old. I
                    met someone that <b>completely</b> changed my vision of
                    astrology. She explained to me that we have a whole birth
                    chart and not just a Sun sign.
                  </div>

                  <div className="mt-5">
                    I became <b>obsessed</b> with astrology and I always wanted
                    to get the birth info of people to look at their birth chart
                    (we all did this lol). I had discovered a magic tool that
                    made me able to truly understand myself and others.
                  </div>

                  <div className="mt-5">
                    At this time I was at high school and I was talking{" "}
                    <u>all the time</u> to my friends, my family and my
                    boyfriend about astrology (they even got annoyed at some
                    points lol). But the truth was that I just loved{" "}
                    <b>help them with astrology.</b>
                  </div>

                  <div className="mt-5">
                    At this time, I was very depressed. I hated high school. I
                    had the feeling to lose my time learning things I don’t care
                    about. I was isolated in my friends group. To make it
                    simple, I was feeling at the <i>wrong place</i>.
                  </div>

                  <div className="mt-5">
                    So, I ended up quitting high school overnight in my last
                    year and <i>I moved from Switzerland to Malaysia at 17</i>{" "}
                    (thanks to my boyfriend for his help).
                  </div>

                  <div className="mt-5">
                    Here I became <b>happy</b> like never. But… I was still{" "}
                    <b>lost</b> about what to do. I had so many passion but I
                    always ended up give up all of them.
                  </div>

                  <div className="mt-5">
                    One day, I had a discussion with my boyfriend about{" "}
                    <i>what should I do in my life</i>. And he told me: “What
                    about astrology? You keep talking about it to me all the
                    time”.
                  </div>

                  <div className="mt-5">
                    I realised astrology has always been{" "}
                    <b>my biggest passion</b>. So it’s how I decided to go all
                    in learning astrology. And finally become an astrologer to
                    help others becoming <i>happy</i>
                    and <i>changing their life</i>.
                  </div>
                </div>
              </div>
            </div>

            {/* Section 3 */}
            <div className="lg:grid grid-cols-3 flex flex-col-reverse lg:mt-32 mt-14">
              <div className="col-span-2 flex lg:pr-20 items-center">
                <div className="lg:text-xl text-lg">
                  <div className="mb-5 font-bold lg:text-3xl text-xl">
                    My Learning & Journey
                  </div>
                  <div>
                    Everyone that start learning astrology will feel this: there
                    is a <b>crazy huge</b> amount of data to learn and
                    understand about astrology. Without surprise, I felt the
                    same.
                  </div>

                  <div className="mt-5">
                    But I was so passionate that it didn’t stopped me. So, after
                    few years of intensive learning,<b> I made it</b>. I
                    mastered enough the symbols and techniques of astrology
                    (even if we never really master it completely lol) and
                    became an <i>astrologer</i>.
                  </div>

                  <div className="mt-5">
                    I know, you probably wonder: “what did you do to achieve
                    this??”
                  </div>

                  <div className="mt-5">
                    The answer is simple: I didn’t rest lol.
                  </div>

                  <div className="mt-5">
                    No seriously, I had to go through{" "}
                    <b>+300 hours of podcasts and videos</b>. Dozens of French
                    and English <b>astrology books</b>. Many{" "}
                    <b>online courses</b> like The Professional Astrologer
                    Course by Chris Brennan and the{" "}
                    <i>Career and Life Direction in Astrology</i> course by
                    Kelly Surtees.
                  </div>

                  <div className="mt-5">
                    You think that’s a lot? That’s not finish! (it would be too
                    easy)
                  </div>

                  <div className="mt-5">
                    I had also to go through{" "}
                    <b>hundreds of hours of practice</b> by reading{" "}
                    <b>+100 charts</b> for people around the world (but also my
                    family and friends) before doing it professionally.
                  </div>

                  <div className="mt-5">
                    But honestly, what taught me the most was…
                  </div>

                  <div className="mt-5">
                    Applying astrology in my <i>daily life</i>. Anytime I wanted
                    to understand a situation, I looked at my transits,
                    someone’s birth chart, the synastry chart and whatever thing
                    that could help me understand what was going on…
                  </div>

                  <div className="mt-5">
                    To make it simple, I truly learned astrology by my own{" "}
                    <b>everyday observations</b> on myself and others.
                  </div>

                  <div className="mt-5">
                    My main influences in my astrology learning are:{" "}
                    <OutBoundLink href="https://www.chrisbrennanastrologer.com/">
                      Chris Brennan
                    </OutBoundLink>
                    ,{" "}
                    <OutBoundLink href="https://www.sebastien-michel.com/">
                      Sebastien Michel
                    </OutBoundLink>
                    ,{" "}
                    <OutBoundLink href="https://www.forrestastrology.com/">
                      Steven Forrest
                    </OutBoundLink>
                    ,{" "}
                    <OutBoundLink href="https://loureinnobrac.fr/astrologie/">
                      Lou Reinnobrac
                    </OutBoundLink>
                    ,{" "}
                    <OutBoundLink href="https://www.kellysastrology.com/">
                      Kelly Surtees
                    </OutBoundLink>{" "}
                    and{" "}
                    <OutBoundLink href="https://francois-barthomeuf.com/">
                      François Barthomeuf
                    </OutBoundLink>
                    .
                  </div>
                </div>
              </div>
              <div className="col-span-1 lg:flex hidden items-center justify-end">
                <Image
                  className="rounded-full"
                  src="/images/about-face.jpeg"
                  alt=""
                  width={340}
                  height={400}
                />
              </div>

              <div className="lg:hidden flex justify-center mb-10">
                <Image
                  className="rounded-full"
                  src="/images/about-face.jpeg"
                  alt=""
                  width={200}
                  height={200}
                />
              </div>
            </div>

            {/* Section 4 */}
            <div className="lg:mt-32 mt-14">
              <div className="lg:text-xl text-lg">
                <div className="mb-5 font-bold lg:text-3xl text-xl">
                  The 5 Reasons Why I Chose Astrology
                </div>

                <div>
                  <div className="font-bold mb-2 lg:text-2xl text-xl">
                    #1 You never stop learning
                  </div>
                  <p>
                    Even if I would put my whole life in reading all the
                    astrology books, watch all the videos and take all the
                    courses, I wouldn’t even learn half of it! I just{" "}
                    <b>love learning</b> and feeling like an eternal student.
                    Never stopping to discover new things about astrology makes
                    my passion for it grow even more!
                  </p>
                </div>

                <div className="mt-5">
                  <div className="font-bold mb-2 lg:text-2xl text-xl">
                    #2 You Can Truly Understand Yourself And Others.
                  </div>
                  <p>
                    What made me fall in love for astrology is really this one
                    thing: being able to <u>understand human behaviors</u>{" "}
                    (psychology basically). Their emotions, tastes, fears,
                    relationships and whatever you can imagine. Honestly,
                    psychology is really fascinating but astrology makes it{" "}
                    <i>clearer, easier and more accurate!</i>
                  </p>
                </div>

                <div className="mt-5">
                  <div className="font-bold mb-2 lg:text-2xl text-xl">
                    #3 It’s A Meaning Of Life.
                  </div>
                  <p>
                    When you learn astrology, you will think about it all the
                    time. Simply because it’s <u>everywhere</u>! Astrology
                    explain to us what we are meant to do in this life. But also
                    that we are deeply connected to the Universe!
                  </p>
                </div>

                <div className="mt-5">
                  <div className="font-bold mb-2 lg:text-2xl text-xl">
                    #4 It’s Not Just Astrology.
                  </div>
                  <p>
                    To make it simple, astrology is a{" "}
                    <b>really complete discipline</b>: psychology, mathematics,
                    mythology, history, and way more. If you want to become
                    astrologer nowadays, you need to master social media,
                    marketing, writing, etc. As a very versatile person, I just{" "}
                    <i>love this</i>.
                  </p>
                </div>

                <div className="mt-5">
                  <div className="font-bold mb-2 lg:text-2xl text-xl">
                    #5 You Can Help Others.
                  </div>
                  <p>
                    My <u>biggest satisfaction</u> is when I can{" "}
                    <b>truly help someone</b>. Seeing people evolving, becoming
                    who they truly want and being happy… it’s just filling my
                    heart with happiness. It’s one of the biggest reason I
                    wanted to start practicing astrology professionally.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <CallToAction />
      </main>

      <Footer hideBg />
    </div>
  );
};

export default About;
