import Head from "next/head";
import Image from "next/image";
import React from "react";
import CallToAction from "../components/UI/CallToAction";
import Footer from "../components/UI/Footer";
import Navbar from "../components/UI/Navbar";
import SectionHead from "../components/UI/SectionHead";
import socials from "../json/socialMedias.json";

const contact = () => {
  return (
    <div>
      <Head>
        <title>About | Easy Astrology By Zoée</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo-color.png" />
      </Head>

      <Navbar />

      <main className="text-white">
        <SectionHead title={"Contact Me"} />
        <div className="bg-green py-32">
          <div className="container-deep">
            <div className="grid grid-cols-3">
              <div className="col-span-1 text-lg font-semibold">
                <div>
                  <div className="text-xl font-bold mb-5">Social Media</div>
                  {socials.map((social) => (
                    <a
                      href={social.link}
                      target={"_blank"}
                      rel="noreferrer noopener"
                      className="flex items-center mb-5 w-max smooth hover:opacity-70"
                      key={`contact-social-${social.name}`}
                    >
                      <Image src={social.image} alt="" height={30} width={30} />
                      <span className="ml-3">{social.tag}</span>
                    </a>
                  ))}
                </div>

                <div className="mt-10">
                  <div className="text-xl font-bold mb-3">Others</div>
                  <a
                    href={"mailto:yew6933@gmail.com"}
                    className="flex items-center w-max smooth hover:opacity-70"
                  >
                    <Image
                      src={"/images/icon_mail.png"}
                      alt=""
                      height={30}
                      width={30}
                    />
                    <span className="ml-3">yew6933@gmail.com</span>
                  </a>
                </div>
              </div>

              <div className="col-span-2 pl-40">
                <form
                  name="contact"
                  method="POST"
                  data-netlify="true"
                  className="w-full"
                >
                  <input type="hidden" name="form-name" value="contact" />
                  <div className="mb-4">
                    <label className="block font-semibold mb-2" htmlFor="name">
                      Name
                    </label>
                    <input
                      className="appearance-none outline-none border-2 border-white rounded w-full py-2 px-3 text-black leading-tight focus:border-gray-600"
                      id="name"
                      type="text"
                      name="name"
                      placeholder="John Doe"
                      required
                    />
                  </div>

                  <div className="mb-4">
                    <label className="block font-semibold mb-2" htmlFor="email">
                      E-mail
                    </label>
                    <input
                      className="appearance-none outline-none border-2 border-white rounded w-full py-2 px-3 text-black leading-tight focus:border-gray-600"
                      id="email"
                      type="email"
                      name="email"
                      placeholder="johndoe@example.com"
                      required
                    />
                  </div>

                  <div className="mb-6">
                    <label
                      className="block font-semibold mb-2"
                      htmlFor="message"
                    >
                      Message
                    </label>
                    <textarea
                      className="appearance-none outline-none border-2 border-white rounded w-full py-2 px-3 text-black leading-tight focus:border-gray-600"
                      id="message"
                      name="message"
                      placeholder="Type your message here..."
                      rows={8}
                      required
                    />
                  </div>

                  <button
                    className="border-2 border-white px-12 py-3 hover:bg-white hover:text-black smooth lg:text-xl text-lg"
                    type="submit"
                  >
                    Send
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
        <CallToAction />
      </main>

      <Footer />
    </div>
  );
};

export default contact;
