import Head from "next/head";
import { useRef } from "react";
import Hero from "../components/Home/Hero";
import Navbar from "../components/Navbar";

export default function Home() {
  const servicesRef = useRef();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main>
        <div position={"relative"}>
          <Hero />
          <div
            className="scroll-down"
            onClick={() => {
              servicesRef.current.scrollIntoView({
                behavior: "smooth",
              });
            }}
          ></div>
        </div>

        <div ref={servicesRef} height={"100vh"} width="100%"></div>
      </main>
    </div>
  );
}
