import Head from "next/head";
import { useRef } from "react";
import CallToAction from "../components/UI/CallToAction";
import Footer from "../components/UI/Footer";
import AboutMe from "../components/Home/AboutMe";
import FAQ from "../components/Home/FAQ";
import Hero from "../components/Home/Hero";
import Services from "../components/Home/Services";
import SocialMedia from "../components/Home/SocialMedia";
import Testimonial from "../components/Home/Testimonial";
import Navbar from "../components/UI/Navbar";
import Script from "next/script";

export default function Home() {
  const servicesRef = useRef();
  return (
    <div className="relative">
      <Script src="https://platform.twitter.com/widgets.js" async />

      <Head>
        <title>Home | Easy Astrology By Zoée</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo-color.png" />
      </Head>

      <Navbar />

      <main>
        <div>
          <Hero />
          <div
            className="scroll-down"
            onClick={() => {
              servicesRef.current.scrollIntoView({
                behavior: "smooth",
              });
            }}
          ></div>
        </div>
        <div id="testimonials" ref={servicesRef}>
          <Testimonial />
        </div>

        <div id="services">
          <Services />
        </div>

        <div>
          <AboutMe />
        </div>

        <div>
          <FAQ />
        </div>

        <div id="social">
          <SocialMedia />
        </div>

        <CallToAction />
      </main>

      <Footer hideBg={true} />
    </div>
  );
}
