import Head from "next/head";
import Image from "next/image";
import React from "react";
import BgOverlay from "../components/BgOverlay";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import SectionHead from "../components/SectionHead";
import CoachingAstrology from "../components/Services/CoachingAstrology";

const Services = () => {
  return (
    <div>
      <Head>
        <title>Services | Easy Astrology By Zoée</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo-color.png" />
      </Head>

      <Navbar />

      <main className="text-white">
        <SectionHead title={"Services"} />

        <div className="bg-green py-20">
          <div className="container-deep">
            <div className="mb-20">
              <CoachingAstrology />
            </div>

            <CoachingAstrology />
          </div>
        </div>

        <div
          className="text-white bg-green text-center relative"
          style={{
            background:
              "url(/images/hero-bg.jpg) no-repeat center center / cover",
          }}
        >
          <BgOverlay opacity={"0.4"} />
          <div className="relative py-20">
            <div className="mb-8 text-5xl font-semibold">Work with me</div>
            <button className="btn text-xl font-semibold"></button>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};
export default Services;
