import Head from "next/head";
import Image from "next/image";
import React from "react";
import BgOverlay from "../components/BgOverlay";
import CallToAction from "../components/CallToAction";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import SectionHead from "../components/SectionHead";
import CoachingAstrology from "../components/Services/CoachingAstrology";
import FollowUp from "../components/Services/FollowUp";
import Synastry from "../components/Services/Synastry";

const Services = () => {
  return (
    <div>
      <Head>
        <title>Services | Easy Astrology By Zoée</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo-color.png" />
      </Head>

      <Navbar />

      <main className="text-white">
        <SectionHead title={"Services"} />

        <div className="bg-green py-20">
          <div className="container">
            <div className="mb-20">
              <CoachingAstrology />
            </div>

            <div className="mb-20">
              <FollowUp />
            </div>

            <div className="mb-20">
              <Synastry />
            </div>
          </div>
        </div>

        <CallToAction />
      </main>

      <Footer />
    </div>
  );
};
export default Services;
